# Generated by Django 5.0.1 on 2024-04-07 17:47

import autoslug.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import easy_thumbnails.fields
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsPagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('CR', 'Creado'), ('PB', 'Publicado')], default='CR', max_length=2)),
                ('imagen', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='pasos_pics')),
                ('categoria', models.CharField(choices=[('car', 'Carne'), ('pes', 'Pescado'), ('ave', 'Ave'), ('cal', 'Caldo'), ('ens', 'Ensalada'), ('pas', 'Pasta'), ('pos', 'Postre'), ('sop', 'Sopa'), ('ver', 'Verdura'), ('otr', 'Otro')], default='ning', max_length=25)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='titulo', unique=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['fecha_creacion', 'fecha_modificacion'],
            },
        ),
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('cantidad', models.CharField(max_length=250)),
                ('recetas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.itemspagina')),
            ],
        ),
        migrations.CreateModel(
            name='Pasos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('descripcion', models.CharField(max_length=250)),
                ('imagen_paso', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='recetas_pics')),
                ('tiempo_preparacion', models.IntegerField()),
                ('tiempo_coccion', models.IntegerField()),
                ('recetas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.itemspagina')),
            ],
        ),
        migrations.AddIndex(
            model_name='itemspagina',
            index=models.Index(fields=['titulo'], name='titulo_index', opclasses=['varchar_pattern_ops']),
        ),
        migrations.AddIndex(
            model_name='itemspagina',
            index=models.Index(fields=['-fecha_creacion', 'categoria'], name='core_itemsp_fecha_c_d00a25_idx'),
        ),
        migrations.AddIndex(
            model_name='itemspagina',
            index=django.contrib.postgres.indexes.GinIndex(fields=['titulo'], name='titulo_gin_index', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='ingredientes',
            index=django.contrib.postgres.indexes.GinIndex(fields=['nombre'], name='nombre_gin_index', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='pasos',
            index=django.contrib.postgres.indexes.GinIndex(fields=['descripcion'], name='descripcion_gin_index', opclasses=['gin_trgm_ops']),
        ),
    ]
