# Generated by Django 5.0.1 on 2024-04-02 15:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemspagina',
            options={'ordering': ['fecha_creacion', 'fecha_modificacion']},
        ),
        migrations.AddField(
            model_name='itemspagina',
            name='categoria',
            field=models.CharField(default='Ninguna'),
        ),
        migrations.AddField(
            model_name='itemspagina',
            name='status',
            field=models.CharField(choices=[('CR', 'Creado'), ('PB', 'Publicado')], default='CR', max_length=2),
        ),
        migrations.AddIndex(
            model_name='itemspagina',
            index=models.Index(fields=['-fecha_creacion', 'categoria'], name='core_itemsp_fecha_c_d00a25_idx'),
        ),
    ]
