# Generated by Django 5.0.1 on 2024-04-16 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pasos',
            options={'ordering': ['numero']},
        ),
        migrations.AlterField(
            model_name='pasos',
            name='imagen_paso',
            field=models.ImageField(blank=True, null=True, upload_to='recetas_pics'),
        ),
    ]
