# Generated by Django 5.0.1 on 2024-04-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_itemspagina_options_itemspagina_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pasos',
            old_name='imagen',
            new_name='imagen_paso',
        ),
        migrations.AddField(
            model_name='pasos',
            name='tiempo_coccion',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
