# Generated by Django 5.0.1 on 2024-04-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pasos_options_alter_pasos_imagen_paso'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemspagina',
            name='autor',
            field=models.CharField(default='Lucas', max_length=100),
        ),
    ]
