# Generated by Django 5.0.1 on 2024-04-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_itemspagina_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemspagina',
            name='categoria',
            field=models.CharField(choices=[('carne', 'Carne'), ('pescado', 'Pescado'), ('ave', 'Ave'), ('caldo', 'Caldo'), ('ensalada', 'Ensalada'), ('pasta', 'Pasta'), ('postre', 'Postre'), ('sopa', 'Sopa'), ('verdura', 'Verdura'), ('otro', 'Otro')], default='ning', max_length=25),
        ),
    ]
