# Generated by Django 5.0.1 on 2024-05-02 07:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_itemspagina_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='FondosHeaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vista', models.CharField(blank=True, max_length=100)),
                ('imagen_fondo', models.ImageField(default='default.jpg', upload_to='imagenes_fondo/')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Encabezados del sitio',
                'verbose_name_plural': 'Encabezados del sitio',
            },
        ),
    ]
