# Generated by Django 5.0.1 on 2024-05-02 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fondosheaders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='categorias')),
            ],
        ),
        migrations.RenameIndex(
            model_name='itemspagina',
            new_name='core_itemsp_fecha_c_09ba96_idx',
            old_name='core_itemsp_fecha_c_d00a25_idx',
        ),
        migrations.AlterField(
            model_name='itemspagina',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoria'),
        ),
    ]
