# Generated by Django 5.0.1 on 2024-05-13 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_categoria_nombre'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='itemspagina',
            name='titulo_index',
        ),
    ]
