# Generated by Django 5.0.1 on 2024-10-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_itemspagina_titulo_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemspagina',
            name='likes',
        ),
        migrations.AlterField(
            model_name='ingredientes',
            name='cantidad',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
