# Generated by Django 5.0.1 on 2024-10-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_itemspagina_likes_alter_ingredientes_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasos',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
