# Generated by Django 5.0.1 on 2024-10-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_pasos_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientes',
            name='cantidad',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='ingredientes',
            name='nombre',
            field=models.CharField(max_length=1000),
        ),
    ]
