# Generated by Django 5.0.1 on 2024-04-07 23:28

import autoslug.fields
import easy_thumbnails.fields
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('descripcion', models.TextField()),
                ('usos', models.CharField(max_length=500)),
                ('link_amazon', models.URLField(blank=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='titulo', unique=True)),
                ('imagen', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='pasos_pics')),
                ('status', models.CharField(choices=[('CR', 'Creado'), ('PB', 'Publicado')], default='CR', max_length=2)),
                ('likes', models.ManyToManyField(blank=True, related_name='menaje_likes', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
