# Generated by Django 5.0.1 on 2024-04-10 14:04

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menaje', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menaje',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='nombre', unique=True),
        ),
    ]
