# Generated by Django 5.0.1 on 2024-04-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menaje', '0002_alter_menaje_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='menaje',
            name='categorias',
            field=models.ManyToManyField(to='menaje.categoria'),
        ),
    ]
