# Generated by Django 5.0.1 on 2024-04-16 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menaje', '0003_categoria_menaje_categorias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menaje',
            old_name='categorias',
            new_name='categoria',
        ),
    ]
