# Generated by Django 5.0.1 on 2024-04-10 14:04

import autoslug.fields
import django.db.models.deletion
import easy_thumbnails.fields
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aparatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField()),
                ('usos', models.TextField()),
                ('caracteristica_generales', models.TextField()),
                ('imagen', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='pasos_pics')),
                ('status', models.CharField(choices=[('CR', 'Creado'), ('PB', 'Publicado')], default='CR', max_length=2)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nombre', unique=True)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('categorias', models.ManyToManyField(to='aparatos.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Modelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('link_amazon', models.URLField(blank=True)),
                ('caracteristicas_modelo', models.TextField()),
                ('año', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CR', 'Creado'), ('PB', 'Publicado')], default='CR', max_length=2)),
                ('imagen', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='pasos_pics')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nombre', unique=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True)),
                ('categorias', models.ManyToManyField(to='aparatos.categoria')),
                ('likes', models.ManyToManyField(blank=True, related_name='aparatos_likes', to=settings.AUTH_USER_MODEL)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aparatos.aparatos')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
