# Generated by Django 5.0.1 on 2024-04-16 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aparatos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aparatos',
            old_name='categorias',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='modelos',
            old_name='categorias',
            new_name='categoria',
        ),
    ]
