# Generated by Django 5.0.1 on 2024-05-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparatos', '0003_remove_modelos_categoria_alter_aparatos_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='categorias_recetas'),
        ),
    ]
