# Generated by Django 5.0.1 on 2024-05-06 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparatos', '0004_categoria_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aparatos',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='categorias_recetas'),
        ),
        migrations.AddField(
            model_name='aparatos',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aparatos.categoria'),
        ),
    ]
