# Generated by Django 5.0.1 on 2024-05-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparatos', '0005_remove_aparatos_categoria_alter_categoria_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aparatos',
            name='link_amazon',
            field=models.URLField(blank=True),
        ),
    ]
